"""Path registry and send-helper for the four DOCX user guides.

The actual files live under docs/user_guides/ and are regenerated by
scripts/build_user_guides.py. The bot only ships them as static documents.
"""
from __future__ import annotations

from pathlib import Path

from aiogram.types import FSInputFile


_ROOT = Path(__file__).resolve().parent.parent
USER_GUIDE_DIR = _ROOT / "docs" / "user_guides"

USER_GUIDE_FILES: dict[str, Path] = {
    "student_adult":  USER_GUIDE_DIR / "user_guide_student_adult.docx",
    "student_school": USER_GUIDE_DIR / "user_guide_student_school.docx",
    "parent":         USER_GUIDE_DIR / "user_guide_parent.docx",
    "admin":          USER_GUIDE_DIR / "user_guide_admin.docx",
}

USER_GUIDE_TITLES: dict[str, str] = {
    "student_adult":  "Инструкция к боту — для взрослого ученика",
    "student_school": "Инструкция к боту — для школьника",
    "parent":         "Инструкция к боту — для родителя",
    "admin":          "Инструкция к боту — для преподавателя",
}


def is_valid_guide_kind(kind: str) -> bool:
    return kind in USER_GUIDE_FILES


async def send_user_guide(bot, chat_id: int, kind: str) -> bool:
    """Send the requested DOCX guide to the chat. Returns False if the file is missing."""
    path = USER_GUIDE_FILES.get(kind)
    if not path or not path.exists():
        return False
    await bot.send_document(
        chat_id,
        FSInputFile(str(path)),
        caption=USER_GUIDE_TITLES[kind],
    )
    return True
